version: '3.8'

services:
  mongodb:
    image: mongo:latest # Or a specific version like mongo:6.0
    container_name: mongodb_container
    ports:
      - "27017:27017" # Map host port 27017 to container port 27017
    volumes:
      - mongodb_data:/data/db # Persist data in a named volume
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: P@ssw0rd2025
    restart: always

volumes:
  mongodb_data:
    driver: local # Define the named volume